wandb_version: 1

activation_function:
  value: relu
batch:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 64
learning_rate:
  value: 0.001
num_hidden_layers:
  value: 4
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_initialisation:
  value: random
