wandb_version: 1

activation_function:
  value: tanh
batch:
  value: 16
epochs:
  value: 10
hidden_layer_size:
  value: 32
learning_rate:
  value: 0.001
num_hidden_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0.5
weight_initialisation:
  value: xavier
