wandb_version: 1

activation_function:
  value: relu
batch:
  value: 32
epochs:
  value: 10
hidden_layer_size:
  value: 32
learning_rate:
  value: 0.003
num_hidden_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0.0005
weight_initialisation:
  value: random
