wandb_version: 1

activation_function:
  value: relu
batch:
  value: 64
epochs:
  value: 5
hidden_layer_size:
  value: 64
learning_rate:
  value: 0.003
num_hidden_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0.5
weight_initialisation:
  value: xavier
