wandb_version: 1

activation_function:
  value: sigmoid
batch:
  value: 16
epochs:
  value: 10
hidden_layer_size:
  value: 128
learning_rate:
  value: 0.0001
num_hidden_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0
weight_initialisation:
  value: random
