wandb_version: 1

activation_function:
  value: relu
batch:
  value: 64
epochs:
  value: 5
hidden_layer_size:
  value: 256
learning_rate:
  value: 0.001
num_hidden_layers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_initialisation:
  value: xavier
