wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1679240414.502153
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 13
      - 23
      4: 3.10.10
      5: 0.13.10
      8:
      - 1
      - 5
activation_function:
  desc: null
  value: tanh
batch:
  desc: null
  value: 16
epochs:
  desc: null
  value: 5
hidden_layer_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.001
num_hidden_layers:
  desc: null
  value: 3
optimizer:
  desc: null
  value: nadam
weight_decay:
  desc: null
  value: 0.0005
weight_initialisation:
  desc: null
  value: xavier
