wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1677672863.381153
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.13.10
      8:
      - 1
      - 5
batch:
  desc: null
  value: 32
epochs:
  desc: null
  value: 5
hidden_layer_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.001
num_hidden_layers:
  desc: null
  value: 3
