wandb_version: 1

activation_function:
  value: sigmoid
batch:
  value: 64
epochs:
  value: 5
hidden_layer_size:
  value: 64
learning_rate:
  value: 0.0001
num_hidden_layers:
  value: 4
optimizer:
  value: nesterov
weight_decay:
  value: 0.5
weight_initialisation:
  value: xavier
