wandb_version: 1

activation_function:
  value: relu
batch:
  value: 64
epochs:
  value: 10
hidden_layer_size:
  value: 64
learning_rate:
  value: 0.001
num_hidden_layers:
  value: 4
optimizer:
  value: nadam
weight_decay:
  value: 0.5
weight_initialisation:
  value: random
