wandb_version: 1

activation_function:
  value: tanh
batch:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 256
learning_rate:
  value: 0.001
num_hidden_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0.0005
weight_initialisation:
  value: xavier
