wandb_version: 1

activation_function:
  value: relu
batch:
  value: 32
epochs:
  value: 10
hidden_layer_size:
  value: 128
learning_rate:
  value: 0.0001
num_hidden_layers:
  value: 4
optimizer:
  value: sgd
weight_decay:
  value: 0.5
weight_initialisation:
  value: xavier
