wandb_version: 1

activation_function:
  value: relu
batch:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 128
learning_rate:
  value: 0.001
num_hidden_layers:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_initialisation:
  value: xavier
