wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1679136725.165608
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.10
      5: 0.13.10
      8:
      - 1
      - 5
activation_function:
  desc: null
  value: relu
batch:
  desc: null
  value: 16
epochs:
  desc: null
  value: 5
hidden_layer_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.0001
num_hidden_layers:
  desc: null
  value: 3
optimizer:
  desc: null
  value: rmsprop
weight_decay:
  desc: null
  value: 0.05
weight_initialisation:
  desc: null
  value: xavier
